---
# tasks file for roles/route53hz
- name: private zone for WEB/ELB endpoints
  route53_zone:
    zone: bgdemo.com
    state: present
    vpc_id: '{{ Vvpc_id }}'
    comment: 'Hosted Zone for Web'
    region: "{{ Vregion }}"
    vpc_region: "{{ Vregion }}"
  register: Rroute53
- debug: msg="{{ Rroute53 }}"

- name: add ELB record in Route53
  route53:
    state: present
    private_zone: yes
    zone: bgdemo.com
    record: web.bgdemo.com
    weight: '{{ item.1 }}'
    identifier: '{{ item.2 }}'
    type: CNAME
    ttl: 60
    value: "{{ item.0 }}"
    overwrite: yes
  with_together:
   - ["{{ Velbdns }}", "{{ Velbdns_blue }}" ]
   - [ 255, 0 ]
   - [ "GreenDeploy", "BlueDeploy" ]
